# Centralized CareerPilot AI Skill & Stack Taxonomy
# Single Source of Truth for Job Families, Skills, Categories, and Normalization

JOB_FAMILIES = {
    "backend_developer": {
        "name": "Backend Developer",
        "signals": ["backend", "server-side", "api", "rest", "database", "microservices", "node.js", "python", "java", "go", "express", "django", "spring", "laravel"],
        "skills": ["node.js", "python", "java", "golang", "express.js", "django", "spring boot", "laravel", "fastapi", "flask", "rest api", "graphql", "sql", "postgresql", "mysql", "mongodb", "redis", "docker", "kubernetes", "aws", "git", "ci/cd", "linux", "bash", "agile", "microservices", "api gateway", "message queue", "kafka", "rabbitmq", "elasticsearch", "nginx", "load balancing", "caching", "authentication", "authorization", "jwt", "oauth", "rate limiting", "webhooks"],
        "descriptions": [
            "Responsible for building and maintaining the server-side logic of web applications.",
            "Designing robust database schemas, optimizing queries, and managing data storage solutions.",
            "Creating scalable RESTful and GraphQL APIs for frontend integration.",
            "Implementing authentication, authorization, and secure communication protocols."
        ]
    },
    "frontend_developer": {
        "name": "Frontend Developer",
        "signals": ["frontend", "client-side", "ui", "react", "vue", "angular", "css", "html", "responsive", "accessibility", "webpack", "vite"],
        "skills": ["javascript", "typescript", "react", "vue", "angular", "html", "css", "sass", "tailwind css", "bootstrap", "webpack", "vite", "redux", "zustand", "tanstack query", "react hook form", "zod", "framer motion", "three.js", "d3.js", "recharts", "socket.io", "websockets", "responsive design", "accessibility", "wcag", "seo", "performance optimization", "pwa", "ssr", "storybook", "jest", "cypress", "playwright", "git", "agile", "figma", "chrome devtools", "lighthouse", "web vitals"],
        "descriptions": [
            "Building highly interactive and responsive web interfaces using modern frameworks.",
            "Collaborating with designers to translate UI/UX mockups into semantic and accessible code.",
            "Optimizing client-side performance, web vitals, and browser rendering paths.",
            "Managing complex frontend state systems and API data fetching pipelines."
        ]
    },
    "fullstack_developer": {
        "name": "Full Stack Developer",
        "signals": ["full stack", "fullstack", "end-to-end", "frontend and backend", "mern", "mean", "jamstack"],
        "skills": ["javascript", "typescript", "react", "node.js", "express.js", "mongodb", "postgresql", "sql", "html", "css", "tailwind css", "rest api", "graphql", "docker", "git", "aws", "ci/cd", "linux", "agile", "redux", "tanstack query", "jwt", "oauth", "redis", "nginx", "webpack", "vite", "jest", "cypress", "responsive design", "accessibility", "seo", "performance optimization", "microservices", "websockets", "socket.io", "pwa", "ssr", "storybook", "figma"],
        "descriptions": [
            "Capable of developing both the frontend user interfaces and the backend API architectures.",
            "Comfortable with database modeling, server orchestration, and client-side styling.",
            "Bridging client-facing features with performant data layer endpoints.",
            "Managing end-to-end development lifecycles from concept to deployment."
        ]
    },
    "devops_engineer": {
        "name": "DevOps Engineer",
        "signals": ["devops", "ci/cd", "pipeline", "infrastructure", "automation", "kubernetes", "docker", "terraform", "ansible", "jenkins"],
        "skills": ["docker", "kubernetes", "terraform", "ansible", "jenkins", "github actions", "gitlab ci", "ci/cd", "linux", "bash", "aws", "azure", "google cloud platform", "prometheus", "grafana", "elk stack", "datadog", "nginx", "helm", "argocd", "istio", "vault", "consul", "packer", "vagrant", "git", "python", "golang", "agile", "microservices", "load balancing", "ssl/tls", "dns", "cdn", "monitoring", "logging", "alerting", "incident response", "on-call", "runbooks", "chaos engineering", "blue-green deployment", "canary release", "feature flags", "infrastructure as code"],
        "descriptions": [
            "Automating deployment pipelines, code compilation, and infrastructure setups.",
            "Configuring cloud platforms, cluster resource orchestration, and container registries.",
            "Ensuring high availability, system uptime, and server monitoring dashboards.",
            "Designing infrastructure-as-code setups for reproducible and secure environments."
        ]
    },
    "cloud_engineer": {
        "name": "Cloud Engineer",
        "signals": ["cloud", "aws", "azure", "gcp", "cloud infrastructure", "cloud migration", "cloud native"],
        "skills": ["aws", "azure", "google cloud platform", "terraform", "cloudformation", "pulumi", "docker", "kubernetes", "lambda", "ec2", "s3", "rds", "dynamodb", "cloudfront", "iam", "vpc", "route53", "cloudwatch", "ecs", "eks", "fargate", "serverless", "api gateway", "sqs", "sns", "kinesis", "step functions", "cloudtrail", "config", "guardduty", "secrets manager"],
        "descriptions": [
            "Designing and implementing secure, resilient cloud architecture blueprints.",
            "Managing virtual private networks, load balancers, access controls, and identity groups.",
            "Migrating legacy on-premise applications to modern serverless and cloud setups.",
            "Optimizing resource utilization, data storage, and compute costs."
        ]
    },
    "data_scientist": {
        "name": "Data Scientist",
        "signals": ["data science", "statistics", "machine learning", "predictive", "modeling", "hypothesis", "experiment", "a/b test"],
        "skills": ["python", "r programming", "pandas", "numpy", "scikit-learn", "tensorflow", "pytorch", "matplotlib", "seaborn", "plotly", "jupyter", "sql", "statistics", "hypothesis testing", "a/b testing", "regression", "classification", "clustering", "time series", "nlp", "deep learning", "feature engineering", "xgboost", "lightgbm", "catboost", "scipy", "statsmodels", "keras", "hugging face", "transformers", "bert", "gpt", "llm", "rag", "vector databases", "pinecone", "chromadb", "mlops", "mlflow", "wandb", "docker", "aws", "bigquery", "snowflake", "spark", "airflow", "dbt", "tableau", "power bi", "excel", "google sheets", "git", "agile", "communication", "storytelling", "presentation", "stakeholder management"],
        "descriptions": [
            "Applying statistical models and quantitative analysis to extract insights from data.",
            "Designing A/B experiments, testing hypotheses, and measuring business metrics.",
            "Building predictive modeling systems and exploratory data visualization dashboards.",
            "Translating complex structured and unstructured datasets into actionable strategies."
        ]
    },
    "ml_engineer": {
        "name": "Machine Learning Engineer",
        "signals": ["machine learning", "ml engineer", "model deployment", "mlops", "training pipeline", "inference", "serving"],
        "skills": ["python", "tensorflow", "pytorch", "scikit-learn", "keras", "xgboost", "lightgbm", "catboost", "pandas", "numpy", "scipy", "matplotlib", "seaborn", "jupyter", "docker", "kubernetes", "aws", "sagemaker", "vertex ai", "azure ml", "mlflow", "wandb", "kubeflow", "airflow", "spark", "hadoop", "hugging face", "transformers", "bert", "gpt", "llm", "rag", "vector databases", "pinecone", "chromadb", "mlops", "feature stores", "model serving", "triton", "onnx", "onnx runtime", "tensorrt", "openvino", "core ml", "tflite", "computer vision", "opencv", "yolo", "nlp", "spacy", "nltk", "fasttext", "word2vec", "glove", "bert", "roberta", "distilbert", "transformer", "vision transformer", "vit", "resnet", "vgg", "alexnet", "efficientnet", "swin transformer"],
        "descriptions": [
            "Building and operationalizing end-to-end machine learning pipelines.",
            "Deploying neural networks, deep learning architectures, and inference engines.",
            "Optimizing training loops, feature stores, and model evaluation metrics.",
            "Integrating trained models into highly concurrent production applications."
        ]
    },
    "ai_engineer": {
        "name": "AI Engineer",
        "signals": ["ai", "artificial intelligence", "llm", "large language model", "gpt", "prompt engineering", "rag", "fine-tuning"],
        "skills": ["python", "tensorflow", "pytorch", "hugging face", "transformers", "bert", "gpt", "llm", "rag", "langchain", "llamaindex", "vector databases", "pinecone", "chromadb", "prompt engineering", "fine-tuning", "rlhf", "mlops", "mlflow", "wandb", "openai", "claude", "gemini", "llama", "mistral", "stable diffusion", "dall-e", "whisper", "opencv", "yolo", "nlp", "spacy", "computer vision", "deep learning", "neural networks", "cnn", "rnn", "lstm", "gru", "attention mechanism", "transformer architecture", "docker", "kubernetes", "aws", "sagemaker", "vertex ai", "git", "agile"],
        "descriptions": [
            "Integrating pre-trained language models, foundation layers, and generative APIs.",
            "Building Retrieval-Augmented Generation (RAG) pipelines and prompt templates.",
            "Managing vector storage systems, semantic search indexes, and agent orchestration.",
            "Fine-tuning models and training alignment protocols like RLHF."
        ]
    },
    "data_analyst": {
        "name": "Data Analyst",
        "signals": ["data analyst", "analytics", "reporting", "dashboard", "insights", "bi", "business intelligence"],
        "skills": ["sql", "excel", "google sheets", "tableau", "power bi", "looker", "metabase", "python", "pandas", "numpy", "matplotlib", "seaborn", "plotly", "r programming", "statistics", "data visualization", "data cleaning", "etl", "data warehousing", "google analytics", "mixpanel", "amplitude", "segment", "dbt", "airflow", "bigquery", "snowflake", "redshift", "postgresql", "mysql", "git", "communication", "storytelling", "presentation", "stakeholder management", "business acumen", "critical thinking", "problem solving", "a/b testing", "hypothesis testing", "regression analysis", "cohort analysis", "funnel analysis", "retention analysis", "churn analysis", "lifetime value"],
        "descriptions": [
            "Performing quantitative analysis, cleaning databases, and resolving anomalies.",
            "Designing business intelligence dashboards, reports, and visual charts.",
            "Analyzing user cohorts, funnels, churn, retention, and lifetime value.",
            "Translating analytical queries into clean executive summaries."
        ]
    },
    "data_engineer": {
        "name": "Data Engineer",
        "signals": ["data engineer", "data pipeline", "etl", "data warehouse", "data lake", "streaming", "batch processing"],
        "skills": ["python", "sql", "spark", "hadoop", "hive", "kafka", "airflow", "dbt", "snowflake", "bigquery", "redshift", "databricks", "aws", "azure", "google cloud platform", "s3", "gcs", "adls", "glue", "emr", "dataflow", "beam", "flink", "storm", "nifi", "talend", "informatica", "fivetran", "airbyte", "stitch", "great expectations", "monte carlo", "collibra", "alation", "docker", "kubernetes", "terraform", "git", "ci/cd", "linux", "bash", "postgresql", "mysql", "mongodb", "cassandra", "dynamodb", "redis", "elasticsearch", "parquet", "avro", "orc", "delta lake", "iceberg", "hudi", "data modeling", "dimensional modeling", "star schema", "slowly changing dimensions", "data governance", "data quality", "data lineage"],
        "descriptions": [
            "Designing and orchestrating scalable data ingestion and processing pipelines.",
            "Maintaining large data warehouses, data lakes, and structured schemas.",
            "Implementing streaming and batch transformations across distributed frameworks.",
            "Ensuring data quality checks, catalogs, lineages, and audit checks."
        ]
    },
    "cybersecurity_analyst": {
        "name": "Cybersecurity Analyst",
        "signals": ["security", "cybersecurity", "soc", "incident response", "vulnerability", "penetration", "siem", "firewall"],
        "skills": ["wireshark", "splunk", "siem", "owasp", "burp suite", "metasploit", "nmap", "kali linux", "penetration testing", "vulnerability assessment", "incident response", "forensics", "malware analysis", "network security", "cryptography", "ssl/tls", "firewall", "ids", "ips", "waf", "ddos protection", "zero trust", "iam", "mfa", "sso", "oauth", "saml", "ldap", "active directory", "windows security", "linux security", "python", "bash", "powershell", "cissp", "ceh", "oscp", "security+", "comptia", "nist", "iso 27001", "gdpr", "hipaa", "pci dss", "soc 2", "risk assessment", "threat modeling", "security audit", "compliance"],
        "descriptions": [
            "Monitoring networks for intrusion, security breaches, and anomalous events.",
            "Conducting penetration tests, vulnerability assessments, and risk reviews.",
            "Responding to security incidents, analyzing malware, and performing forensics.",
            "Enforcing identity access compliance, firewalls, and cryptographic safety."
        ]
    },
    "mobile_developer": {
        "name": "Mobile Developer",
        "signals": ["mobile", "ios", "android", "app", "react native", "flutter", "swift", "kotlin"],
        "skills": ["react native", "flutter", "swift", "kotlin", "dart", "javascript", "typescript", "xcode", "android studio", "firebase", "supabase", "rest api", "graphql", "sqlite", "core data", "room", "jetpack compose", "swiftui", "uikit", "material design", "app store", "google play store", "testflight", "fastlane", "ci/cd", "git", "agile", "push notifications", "deep linking", "offline storage", "caching", "authentication", "biometrics", "in-app purchase", "ads", "analytics", "sentry"],
        "descriptions": [
            "Creating native or cross-platform mobile applications for smartphones and tablets.",
            "Designing intuitive touch layouts, animations, gestures, and haptic feedback.",
            "Integrating local device storage, push alerts, and background execution loops.",
            "Publishing application bundles to app stores and managing releases."
        ]
    },
    "game_developer": {
        "name": "Game Developer",
        "signals": ["game", "gaming", "unity", "unreal", "game engine", "3d", "shader", "gameplay"],
        "skills": ["unity", "unreal engine", "c#", "c++", "godot", "blender", "maya", "3ds max", "cinema 4d", "zbrush", "substance painter", "shaders", "hlsl", "glsl", "cg", "game physics", "collision detection", "pathfinding", "ai behavior trees", "state machines", "animation", "rigging", "particle systems", "vfx", "audio", "fmod", "wwise", "multiplayer", "networking", "photon", "mirror", "steamworks", "game design", "level design", "ui/ux for games", "mobile games", "vr", "ar", "xr"],
        "descriptions": [
            "Designing and coding gameplay mechanics, character physics, and visual layouts.",
            "Programming real-time animation rigs, state machines, and lighting pipelines.",
            "Optimizing multi-threading, memory footprint, and rendering frames per second.",
            "Integrating audio engines, asset packages, and online multiplayer matches."
        ]
    },
    "ux_designer": {
        "name": "UX Designer",
        "signals": ["ux", "user experience", "user research", "wireframe", "prototype", "usability", "persona", "journey map"],
        "skills": ["figma", "sketch", "adobe xd", "invision", "zeplin", "wireframing", "prototyping", "user research", "usability testing", "heuristic evaluation", "information architecture", "interaction design", "visual design", "typography", "color theory", "layout", "grid systems", "responsive design", "accessibility", "wcag", "design systems", "component libraries", "style guides", "user personas", "user journey maps", "empathy maps", "affinity diagrams", "card sorting", "tree testing", "a/b testing", "analytics", "hotjar", "fullstory"],
        "descriptions": [
            "Conducting user interviews, mapping journeys, and creating user personas.",
            "Wireframing interaction architectures and testing wireframe usability.",
            "Analyzing usability tests, tree sorting surveys, and design audits.",
            "Structuring user journeys, interface hierarchies, and system visual states."
        ]
    },
    "product_manager": {
        "name": "Product Manager",
        "signals": ["product manager", "product management", "roadmap", "user stories", "backlog", "prioritization", "stakeholder"],
        "skills": ["roadmap planning", "user stories", "backlog management", "prioritization", "stakeholder management", "agile", "scrum", "kanban", "jira", "confluence", "notion", "linear", "asana", "monday.com", "trello", "miro", "figma", "data analysis", "sql", "excel", "google analytics", "mixpanel", "amplitude", "segment", "a/b testing", "experimentation", "metrics", "kpi", "okr", "north star metric", "funnel analysis", "cohort analysis", "retention", "churn", "ltv", "cac"],
        "descriptions": [
            "Defining product vision, user stories, roadmaps, and prioritizing backlogs.",
            "Coordinating cross-functional engineering, design, and marketing resources.",
            "Tracking product metrics, KPIs, okrs, and north-star retention numbers.",
            "Translating complex customer feedback into structured software specifications."
        ]
    },
    "qa_engineer": {
        "name": "QA Engineer",
        "signals": ["qa", "quality assurance", "testing", "test automation", "selenium", "cypress", "manual testing"],
        "skills": ["selenium", "cypress", "playwright", "jest", "mocha", "chai", "jasmine", "karma", "protractor", "testcafe", "nightwatch", "puppeteer", "appium", "jmeter", "gatling", "locust", "k6", "postman", "newman", "rest assured", "soapui", "junit", "testng", "pytest", "unittest", "robot framework", "cucumber", "gherkin", "bdd", "tdd", "test automation", "manual testing", "regression testing", "smoke testing", "integration testing", "e2e testing", "performance testing", "load testing", "stress testing", "security testing"],
        "descriptions": [
            "Writing automated test scripts for end-to-end user flows and APIs.",
            "Conducting manual, regression, exploratory, integration, and load tests.",
            "Tracking and reporting bug cycles, trace files, and test coverage metrics.",
            "Building quality assurance validation strategies in CI/CD deployment checks."
        ]
    },
    "blockchain_developer": {
        "name": "Blockchain Developer",
        "signals": ["blockchain", "web3", "smart contract", "solidity", "ethereum", "defi", "nft", "dao"],
        "skills": ["solidity", "web3", "ethereum", "smart contracts", "defi", "nft", "dao", "hardhat", "truffle", "foundry", "remix", "openzeppelin", "ethers.js", "web3.js", "viem", "wagmi", "rainbowkit", "metamask", "walletconnect", "ipfs", "arweave", "the graph", "subgraph", "chainlink", "uniswap", "aave", "compound", "makerdao", "lido", "ens", "gnosis safe", "alchemy", "infura", "quicknode", "moralis", "thirdweb", "polygon", "arbitrum", "optimism", "base", "zksync", "starknet", "scroll"],
        "descriptions": [
            "Designing and writing secure smart contracts on distributed virtual machines.",
            "Integrating web3 wallets, decentralized exchange protocols, and token standards.",
            "Optimizing contract transaction costs, gas, and cryptographic security.",
            "Building decentralized application backends using oracle arrays and indexes."
        ]
    },
    "embedded_systems": {
        "name": "Embedded Systems Engineer",
        "signals": ["embedded", "firmware", "microcontroller", "rtos", "iot", "hardware", "pcb"],
        "skills": ["c", "c++", "assembly", "rtos", "freertos", "zephyr", "vxworks", "qnx", "arm", "stm32", "esp32", "arduino", "raspberry pi", "nvidia jetson", "fpga", "verilog", "vhdl", "systemverilog", "pcb design", "altium", "kicad", "eagle", "schematic", "layout", "soldering", "oscilloscope", "logic analyzer", "multimeter", "jtag", "swd", "uart", "spi", "i2c", "can", "modbus", "ethernet", "wifi", "bluetooth", "zigbee", "lorawan", "mqtt", "coap"],
        "descriptions": [
            "Writing bare-metal firmware and real-time operating systems code for chips.",
            "Interfacing with hardware sensors via standard serial and parallel protocols.",
            "Using logic analyzers, oscilloscopes, and multimeters to debug boards.",
            "Developing power-optimized code for microcontrollers and memory-bound chips."
        ]
    }
}


ALIAS_MAP = {
    ".net": ".net",
    ".net core": ".net core",
    ".net framework": ".net framework",
    ".net maui": ".net maui",
    "3ds max": "3ds max",
    "a/b testing": "a/b testing",
    "a3c": "a3c",
    "ab testing": "a/b testing",
    "acceptance testing": "acceptance testing",
    "activemq": "activemq",
    "actor critic": "actor-critic",
    "ad hoc testing": "ad hoc testing",
    "adobe xd": "adobe xd",
    "aeron": "aeron",
    "agile": "agile",
    "aiops": "aiops",
    "airbrake": "airbrake",
    "airflow": "airflow",
    "akamai": "akamai",
    "alibaba cloud": "alibaba cloud",
    "alpha testing": "alpha testing",
    "amazon appstore": "amazon appstore",
    "amazon web services": "aws",
    "amplitude": "amplitude",
    "android studio": "android studio",
    "anomaly detection": "anomaly detection",
    "ansible": "ansible",
    "ant": "ant",
    "ant design": "ant design",
    "apache airflow": "airflow",
    "apache kafka": "kafka",
    "apache spark": "apache spark",
    "api gateway": "api gateway",
    "apisix": "apisix",
    "apk": "apk",
    "apk mirror": "apk mirror",
    "apkpure": "apkpure",
    "app store": "app store",
    "app store connect": "app store connect",
    "appcircle": "appcircle",
    "appdynamics": "appdynamics",
    "appimage": "appimage",
    "appium": "appium",
    "appsignal": "appsignal",
    "apt": "apt",
    "aptoid": "aptoide",
    "argo cd": "argocd",
    "argocd": "argocd",
    "arguments": "arguments",
    "arrow": "apache arrow",
    "async": "async/await",
    "athena": "athena",
    "athens": "athens",
    "atomic": "atomic",
    "auction theory": "auction theory",
    "aura": "aura",
    "aurora store": "aurora store",
    "autoencoders": "autoencoders",
    "automated testing": "automated testing",
    "automation": "automation",
    "avro": "avro",
    "await": "async/await",
    "aws": "aws",
    "aws lambda": "aws lambda",
    "azure": "microsoft azure",
    "azure devops": "azure devops",
    "azure functions": "azure functions",
    "azure ml": "azure ml",
    "babel": "babel",
    "bagging": "bagging",
    "bamboo": "bamboo",
    "bargaining": "bargaining",
    "bash": "bash",
    "bayesian games": "bayesian games",
    "bayesian optimization": "bayesian optimization",
    "beam": "apache beam",
    "bert": "bert",
    "beta testing": "beta testing",
    "bigquery": "bigquery",
    "bitbucket": "git",
    "bitrise": "bitrise",
    "bizdevops": "bizdevops",
    "blazor": "blazor",
    "blender": "blender",
    "blending": "blending",
    "boosting": "boosting",
    "boot": "boot",
    "bootstrap": "bootstrap",
    "bson": "bson",
    "bugsnag": "bugsnag",
    "build engineering": "build engineering",
    "buildah": "buildah",
    "buildkit": "buildkit",
    "buildx": "buildx",
    "bulma": "bulma",
    "bun": "bun",
    "bundler": "bundler",
    "burp suite": "burp suite",
    "c#": "c#",
    "c++": "c++",
    "c4d": "cinema 4d",
    "capn proto": "cap'n proto",
    "cargo": "cargo",
    "carthage": "carthage",
    "cas": "compare and swap",
    "catboost": "catboost",
    "cbor": "cbor",
    "cd": "continuous delivery",
    "cdn": "cdn",
    "ceh": "ceh",
    "cert": "cert",
    "cfgfile": "cfgfile",
    "chai": "chai",
    "chakra ui": "chakra ui",
    "chart.js": "chart.js",
    "chatops": "chatops",
    "checkinstall": "checkinstall",
    "chi testing": "chi testing",
    "chocolatey": "chocolatey",
    "chromadb": "chromadb",
    "ci": "continuous integration",
    "ci cd": "ci/cd",
    "ci/cd": "ci/cd",
    "cicd": "ci/cd",
    "cinema 4d": "cinema 4d",
    "circleci": "circleci",
    "cissp": "cissp",
    "class validator": "class validator",
    "claude": "claude",
    "cleanrl": "cleanrl",
    "cli": "cli",
    "cloudbees": "cloudbees",
    "cloudflare": "cloudflare",
    "cloudflare workers": "cloudflare workers",
    "cloudops": "cloudops",
    "clustering": "clustering",
    "cm": "continuous monitoring",
    "coalitional games": "coalitional games",
    "cocoapods": "cocoapods",
    "codemagic": "codemagic",
    "combinatorial games": "combinatorial games",
    "comfyui": "comfyui",
    "command line": "command line",
    "compare and swap": "compare and swap",
    "compatibility": "compatibility",
    "composer": "composer",
    "computer vision": "computer vision",
    "concourse": "concourse",
    "concurrent": "concurrent",
    "conda": "conda",
    "conffile": "conffile",
    "config": "configuration",
    "configcat": "configcat",
    "configuration": "configuration",
    "console": "console",
    "consul": "consul",
    "containerd": "containerd",
    "containerization": "docker",
    "containers": "docker",
    "continuous delivery": "ci/cd",
    "continuous deployment": "ci/cd",
    "continuous integration": "ci/cd",
    "cooperative games": "cooperative games",
    "core": "core",
    "cpp": "c++",
    "crates.io": "crates.io",
    "cri-o": "cri-o",
    "cross validation": "cross validation",
    "crossplane": "crossplane",
    "cs": "continuous security",
    "csharp": "c#",
    "csv": "csv",
    "csvfile": "csvfile",
    "ct": "continuous testing",
    "cuDF": "cudf",
    "cugraph": "cugraph",
    "cuml": "cuml",
    "cuspatial": "cuspatial",
    "cuxfilter": "cuxfilter",
    "cv": "computer vision",
    "cx": "continuous everything",
    "cypress": "cypress",
    "d3": "d3.js",
    "d3.js": "d3.js",
    "dall-e": "dall-e",
    "dapper": "dapper",
    "dart": "dart",
    "dask": "dask",
    "data lake": "data lake",
    "data pipeline": "data pipeline",
    "data warehousing": "data warehousing",
    "databricks": "databricks",
    "datadog": "datadog",
    "dataops": "dataops",
    "dbscan": "dbscan",
    "dbt": "dbt",
    "decision tree": "decision tree",
    "deep learning": "deep learning",
    "deep q network": "dqn",
    "defi": "defi",
    "deliver": "deliver",
    "delta testing": "delta testing",
    "deno": "deno",
    "deno deploy": "deno deploy",
    "deps.edn": "deps.edn",
    "devops": "devops",
    "devsecops": "devsecops",
    "differential games": "differential games",
    "diffusion models": "diffusion models",
    "digitalocean": "digitalocean",
    "dimensionality reduction": "dimensionality reduction",
    "disruptor": "disruptor",
    "distutils": "distutils",
    "dl": "deep learning",
    "dnf": "dnf",
    "dns": "dns",
    "docker": "docker",
    "docker compose": "docker compose",
    "docker-compose": "docker compose",
    "dockerfile": "dockerfile",
    "dotenv": "dotenv",
    "dotnet": "dotnet",
    "dotnet cli": "dotnet cli",
    "dotnet core": ".net core",
    "dotnet framework": ".net framework",
    "dpkg": "dpkg",
    "draft": "draft",
    "drone": "drone ci",
    "dynatrace": "dynatrace",
    "ef": "entity framework",
    "ef core": "entity framework core",
    "elastic apm": "elastic apm",
    "elasticsearch": "elasticsearch",
    "elk": "elk stack",
    "elk stack": "elk stack",
    "elmo": "elmo",
    "elt": "elt",
    "emerge": "emerge",
    "ensemble methods": "ensemble methods",
    "entity framework": "entity framework",
    "env": "environment variables",
    "envfile": "envfile",
    "environment variables": "environment variables",
    "envoy": "envoy",
    "eppo": "eppo",
    "epsilon testing": "epsilon testing",
    "esbuild": "esbuild",
    "eta testing": "eta testing",
    "ethereum": "ethereum",
    "etl": "etl",
    "evolutionary games": "evolutionary games",
    "excel": "excel",
    "exploratory testing": "exploratory testing",
    "express": "express.js",
    "express.js": "express.js",
    "expressjs": "express.js",
    "extensive form games": "extensive form games",
    "externalities": "externalities",
    "f-droid": "f-droid",
    "faas": "faas",
    "factor analysis": "factor analysis",
    "fastlane": "fastlane",
    "fastly": "fastly",
    "fasttext": "fasttext",
    "feather": "feather",
    "feature engineering": "feature engineering",
    "feature flags": "feature flags",
    "feature selection": "feature selection",
    "fence": "fence",
    "figma": "figma",
    "fine tuning": "fine-tuning",
    "fine-tuning": "fine-tuning",
    "fink": "fink",
    "finops": "finops",
    "firebase": "firebase",
    "flags": "flags",
    "flagsmith": "flagsmith",
    "flatbuffers": "flatbuffers",
    "flatpak": "flatpak",
    "flink": "flink",
    "flipt": "flipt",
    "flit": "flit",
    "fluent bit": "fluent bit",
    "fluentd": "fluentd",
    "flutter": "flutter",
    "flux": "flux",
    "fly.io": "fly.io",
    "formik": "formik",
    "foundation": "foundation",
    "fpm": "fpm",
    "frameit": "frameit",
    "framer motion": "framer motion",
    "freemium": "freemium",
    "fsproj": "fsproj",
    "fullstory": "fullstory",
    "ga4": "google analytics",
    "game theory": "game theory",
    "gamma testing": "gamma testing",
    "gan": "gan",
    "garden": "garden",
    "gatling": "gatling",
    "gaussian mixture": "gaussian mixture",
    "gcp": "google cloud platform",
    "gem": "gem",
    "gemini": "gemini",
    "generative adversarial network": "gan",
    "git": "git",
    "github": "git",
    "github actions": "github actions",
    "gitlab": "git",
    "gitlab ci": "gitlab ci",
    "gitops": "gitops",
    "glitchtip": "glitchtip",
    "glove": "glove",
    "go": "golang",
    "go get": "go get",
    "go mod": "go mod",
    "go modules": "go modules",
    "go.cd": "go.cd",
    "godot": "godot",
    "golang": "golang",
    "gomodproxy": "gomodproxy",
    "google analytics": "google analytics",
    "google cloud": "google cloud platform",
    "google cloud functions": "google cloud functions",
    "google play console": "google play console",
    "google sheets": "google sheets",
    "goproxy": "goproxy",
    "goreleaser": "goreleaser",
    "gpt": "gpt",
    "gpt-3": "gpt",
    "gpt-4": "gpt",
    "gql": "graphql",
    "gradient boosting": "gradient boosting",
    "gradle": "gradle",
    "grafana": "grafana",
    "graphql": "graphql",
    "graylog": "graylog",
    "grid search": "grid search",
    "growthbook": "growthbook",
    "grpc": "grpc",
    "gsap": "gsap",
    "guix": "guix",
    "gym": "gym",
    "gymnasium": "gymnasium",
    "hadoop": "hadoop",
    "hardware lock elision": "hle",
    "hardware transactional memory": "htm",
    "harness": "harness",
    "hatch": "hatch",
    "hdf5": "hdf5",
    "heap": "heap",
    "helm": "helm",
    "heroku": "heroku",
    "hetzner": "hetzner",
    "hierarchical clustering": "hierarchical clustering",
    "highlight": "highlight.io",
    "hive": "hive",
    "hle": "hle",
    "homebrew": "homebrew",
    "honeybadger": "honeybadger",
    "hotjar": "hotjar",
    "htm": "htm",
    "http": "http",
    "http2": "http/2",
    "http3": "http/3",
    "https": "https",
    "huawei appgallery": "huawei appgallery",
    "huawei cloud": "huawei cloud",
    "hugging face": "hugging face",
    "huggingface": "hugging face",
    "hyperopt": "hyperopt",
    "hyperparameter tuning": "hyperparameter tuning",
    "iaas": "iaas",
    "iac": "terraform",
    "ibm cloud": "ibm cloud",
    "ica": "ica",
    "illustrator": "illustrator",
    "infrastructure as code": "terraform",
    "ini": "ini",
    "inifile": "inifile",
    "installpkg": "installpkg",
    "integration testing": "integration testing",
    "interactive": "interactive",
    "interlocked": "interlocked",
    "interoperability": "interoperability",
    "invision": "invision",
    "iota testing": "iota testing",
    "ipkg": "ipkg",
    "isolation forest": "isolation forest",
    "istio": "istio",
    "ivy": "ivy",
    "jaeger": "jaeger",
    "jasmine": "jasmine",
    "javascript": "javascript",
    "jenkins": "jenkins",
    "jest": "jest",
    "jetpack compose": "jetpack compose",
    "jira": "jira",
    "jmeter": "jmeter",
    "joi": "joi",
    "jotai": "jotai",
    "js": "javascript",
    "json": "json",
    "jsonfile": "jsonfile",
    "julia": "julia",
    "k means": "k-means",
    "k nearest neighbors": "knn",
    "k-means": "k-means",
    "k6": "k6",
    "k8s": "kubernetes",
    "kafka": "kafka",
    "kali linux": "kali linux",
    "kanban": "agile",
    "kaniko": "kaniko",
    "kappa testing": "kappa testing",
    "karma": "karma",
    "kibana": "kibana",
    "knn": "knn",
    "kompose": "kompose",
    "kong": "kong",
    "kotlin": "kotlin",
    "kubeflow": "kubeflow",
    "kubernetes": "kubernetes",
    "kustomize": "kustomize",
    "lambda": "aws lambda",
    "lambda testing": "lambda testing",
    "langchain": "langchain",
    "large language model": "llm",
    "large language models": "llm",
    "launchdarkly": "launchdarkly",
    "lda": "lda",
    "leiningen": "leiningen",
    "less": "less",
    "lightgbm": "lightgbm",
    "linear regression": "linear regression",
    "linkerd": "linkerd",
    "linode": "linode",
    "linq": "linq",
    "linq to entities": "linq to entities",
    "linq to objects": "linq to objects",
    "linq to parallel": "linq to parallel",
    "linq to sql": "linq to sql",
    "linq to xml": "linq to xml",
    "linux": "linux",
    "ll sc": "ll/sc",
    "llama": "llama",
    "llamaindex": "llamaindex",
    "llm": "llm",
    "lmax disruptor": "lmax disruptor",
    "load linked": "load linked",
    "load testing": "load testing",
    "lock": "lock",
    "lock elision": "lock elision",
    "lock free": "lock-free",
    "lock free b tree": "lock-free b-tree",
    "lock free circular buffer": "lock-free circular buffer",
    "lock free hash map": "lock-free hash map",
    "lock free list": "lock-free list",
    "lock free mpmc queue": "lock-free mpmc queue",
    "lock free mpsc queue": "lock-free mpsc queue",
    "lock free queue": "lock-free queue",
    "lock free ring buffer": "lock-free ring buffer",
    "lock free skip list": "lock-free skip list",
    "lock free spmc queue": "lock-free spmc queue",
    "lock free spsc queue": "lock-free spsc queue",
    "lock free stack": "lock-free stack",
    "lock free tree": "lock-free tree",
    "lock free trie": "lock-free trie",
    "lock in": "lock-in",
    "locust": "locust",
    "logdna": "logdna",
    "loggly": "loggly",
    "logistic regression": "logistic regression",
    "logrocket": "logrocket",
    "logstash": "logstash",
    "loki": "loki",
    "long polling": "long polling",
    "looker": "looker",
    "lottie": "lottie",
    "mac app store": "mac app store",
    "machine learning": "machine learning",
    "macports": "macports",
    "makepkg": "makepkg",
    "mamba": "mamba",
    "manual testing": "manual testing",
    "market design": "market design",
    "marl": "multi-agent rl",
    "match": "match",
    "matching markets": "matching markets",
    "matching theory": "matching theory",
    "material ui": "material ui",
    "matlab": "matlab",
    "matplotlib": "matplotlib",
    "maui": ".net maui",
    "maven": "maven",
    "maya": "maya",
    "mechanism design": "mechanism design",
    "memcached": "memcached",
    "memory barrier": "memory barrier",
    "messagepack": "messagepack",
    "metabase": "metabase",
    "metasploit": "metasploit",
    "mezmo": "mezmo",
    "microsoft store": "microsoft store",
    "midjourney": "midjourney",
    "milvus": "milvus",
    "minimal api": "minimal api",
    "mistral": "mistral",
    "mixpanel": "mixpanel",
    "ml": "machine learning",
    "ml ops": "mlops",
    "mlflow": "mlflow",
    "mlops": "mlops",
    "mobx": "mobx",
    "mocha": "mocha",
    "modin": "modin",
    "mongo": "mongodb",
    "mongodb": "mongodb",
    "monitor": "monitor",
    "mono": "mono",
    "ms sql": "ms sql server",
    "mssql": "ms sql server",
    "mu testing": "mu testing",
    "mui": "material ui",
    "multi agent": "multi-agent",
    "mutex": "mutex",
    "mvc": "mvc",
    "mysql": "mysql",
    "naive bayes": "naive bayes",
    "named entity recognition": "named entity recognition",
    "nash equilibrium": "nash equilibrium",
    "natural language processing": "nlp",
    "negotiation": "negotiation",
    "ner": "named entity recognition",
    "netcdf": "netcdf",
    "netlify functions": "netlify functions",
    "netops": "netops",
    "network effects": "network effects",
    "new relic": "new relic",
    "nfpm": "nfpm",
    "nft": "nft",
    "nhibernate": "nhibernate",
    "nightwatch": "nightwatch",
    "nivo": "nivo",
    "nix": "nix",
    "nlp": "nlp",
    "nmap": "nmap",
    "node": "node.js",
    "node.js": "node.js",
    "nodejs": "node.js",
    "nomad": "nomad",
    "non blocking": "non-blocking",
    "non cooperative games": "non-cooperative games",
    "noops": "noops",
    "normal form games": "normal form games",
    "nosql": "nosql",
    "npm": "npm",
    "nu testing": "nu testing",
    "nucleolus": "nucleolus",
    "nuget": "nuget",
    "numpy": "numpy",
    "observable": "observable",
    "obstruction free": "obstruction-free",
    "octave": "octave",
    "omega testing": "omega testing",
    "omicron testing": "omicron testing",
    "one class svm": "one-class svm",
    "open source": "open source",
    "openai": "openai",
    "openai gym": "openai gym",
    "opencv": "opencv",
    "opentelemetry": "opentelemetry",
    "opkg": "opkg",
    "optimizely": "optimizely",
    "options": "options",
    "optuna": "optuna",
    "oracle": "oracle db",
    "oracle cloud": "oracle cloud",
    "orc": "orc",
    "orchestration": "orchestration",
    "otel": "opentelemetry",
    "overops": "overops",
    "ovh": "ovh",
    "owasp": "owasp",
    "paas": "paas",
    "packagist": "packagist",
    "packer": "packer",
    "pacman": "pacman",
    "paket": "paket",
    "pandas": "pandas",
    "papertrail": "papertrail",
    "parallel": "parallel",
    "parameters": "parameters",
    "parcel": "parcel",
    "parquet": "parquet",
    "paru": "paru",
    "pca": "pca",
    "pdm": "pdm",
    "pem": "pem",
    "penetration testing": "penetration testing",
    "pentesting": "penetration testing",
    "performance testing": "performance testing",
    "pettingzoo": "pettingzoo",
    "pg": "postgresql",
    "pgvector": "pgvector",
    "phi testing": "phi testing",
    "photoshop": "photoshop",
    "pi testing": "pi testing",
    "pig": "pig",
    "pikaur": "pikaur",
    "pilot": "pilot",
    "pinecone": "pinecone",
    "pip": "pip",
    "pipeline": "pipeline",
    "pipenv": "pipenv",
    "piranha": "piranha",
    "pixi": "pixi",
    "pkg": "pkg",
    "platform economics": "platform economics",
    "platform engineering": "platform engineering",
    "play store": "google play store",
    "playwright": "playwright",
    "plinq": "plinq",
    "plotly": "plotly",
    "pnpm": "pnpm",
    "podman": "podman",
    "poetry": "poetry",
    "polars": "polars",
    "policy gradient": "policy gradient",
    "portage": "portage",
    "postcss": "postcss",
    "postgres": "postgresql",
    "postgresql": "postgresql",
    "posthog": "posthog",
    "power bi": "power bi",
    "ppo": "ppo",
    "preferences": "preferences",
    "produce": "produce",
    "production engineering": "production engineering",
    "prometheus": "prometheus",
    "prompt": "prompt",
    "prompt engineering": "prompt engineering",
    "propertiesfile": "propertiesfile",
    "proprietary": "proprietary",
    "protobuf": "protobuf",
    "protocol buffers": "protobuf",
    "prototyping": "prototyping",
    "protractor": "protractor",
    "psi testing": "psi testing",
    "public goods": "public goods",
    "pulumi": "pulumi",
    "puppeteer": "puppeteer",
    "pypi": "pypi",
    "pytorch": "pytorch",
    "q learning": "q-learning",
    "qa engineering": "qa engineering",
    "qdrant": "qdrant",
    "quality assurance": "quality assurance",
    "quality engineering": "quality engineering",
    "quic": "quic",
    "r": "r programming",
    "r programming": "r programming",
    "rabbitmq": "rabbitmq",
    "rag": "rag",
    "railway": "railway",
    "random forest": "random forest",
    "random search": "random search",
    "rapids": "rapids",
    "ray": "ray",
    "ray rllib": "ray rllib",
    "raygun": "raygun",
    "razor": "razor",
    "razor pages": "razor pages",
    "rcfile": "rcfile",
    "react": "react",
    "react hook form": "react hook form",
    "react native": "react native",
    "react query": "tanstack query",
    "react.js": "react",
    "reactjs": "react",
    "reader writer lock": "readerwriterlock",
    "readerwriterlock": "readerwriterlock",
    "recharts": "recharts",
    "recoil": "recoil",
    "redis": "redis",
    "redshift": "redshift",
    "redux": "redux",
    "regression testing": "regression testing",
    "reinforcement learning": "reinforcement learning",
    "release engineering": "release engineering",
    "removepkg": "removepkg",
    "render": "render",
    "repeated games": "repeated games",
    "repl": "repl",
    "rest": "rest api",
    "rest api": "rest api",
    "rest apis": "rest api",
    "restful": "rest api",
    "restricted transactional memory": "rtm",
    "retrieval augmented generation": "rag",
    "rho testing": "rho testing",
    "rl": "reinforcement learning",
    "rlhf": "rlhf",
    "rn": "react native",
    "rollbar": "rollbar",
    "rollout": "rollout",
    "rollup": "rollup",
    "rpm": "rpm",
    "rtm": "rtm",
    "rubygems": "rubygems",
    "rudderstack": "rudderstack",
    "runc": "runc",
    "rye": "rye",
    "saas": "saas",
    "sac": "sac",
    "sagemaker": "sagemaker",
    "samsung galaxy store": "samsung galaxy store",
    "sanity testing": "sanity testing",
    "sas": "sas",
    "sass": "sass",
    "sbe": "sbe",
    "sbopkg": "sbopkg",
    "sbt": "sbt",
    "scaleway": "scaleway",
    "scan": "scan",
    "scikit learn": "scikit-learn",
    "scikit-learn": "scikit-learn",
    "scikit-optimize": "scikit-optimize",
    "scipy": "scipy",
    "scoop": "scoop",
    "scripting": "scripting",
    "scrum": "agile",
    "scss": "scss",
    "seaborn": "seaborn",
    "secops": "secops",
    "segment": "segment",
    "selenium": "selenium",
    "semantic ui": "semantic ui",
    "semaphore": "semaphore",
    "sentiment analysis": "sentiment analysis",
    "sentry": "sentry",
    "sequencefile": "sequencefile",
    "server sent events": "server-sent events",
    "serverless": "serverless",
    "settings": "settings",
    "setuptools": "setuptools",
    "shapley value": "shapley value",
    "shell": "shell",
    "shell scripting": "bash",
    "short polling": "short polling",
    "siem": "siem",
    "sigh": "sigh",
    "sigma testing": "sigma testing",
    "signalr": "signalr",
    "simple binary encoding": "sbe",
    "site reliability engineering": "sre",
    "skaffold": "skaffold",
    "sketch": "sketch",
    "sklearn": "scikit-learn",
    "skopeo": "skopeo",
    "slackpkg": "slackpkg",
    "slapt-get": "slapt-get",
    "smart contracts": "smart contracts",
    "smoke testing": "smoke testing",
    "snap": "snap",
    "snap store": "snap store",
    "snapshot": "snapshot",
    "snowflake": "snowflake",
    "social choice": "social choice",
    "socket.io": "socket.io",
    "software transactional memory": "stm",
    "solidity": "solidity",
    "spark": "apache spark",
    "spinlock": "spinlock",
    "spinnaker": "spinnaker",
    "split": "split.io",
    "splunk": "splunk",
    "spm": "swift package manager",
    "spss": "spss",
    "sql": "sql",
    "sqlite": "sqlite",
    "sqs": "aws sqs",
    "sre": "sre",
    "sse": "server-sent events",
    "ssl": "ssl/tls",
    "stable baselines": "stable baselines3",
    "stable diffusion": "stable diffusion",
    "stacking": "stacking",
    "standards": "standards",
    "stata": "stata",
    "statsig": "statsig",
    "statsmodels": "statsmodels",
    "stm": "stm",
    "stochastic games": "stochastic games",
    "store conditional": "store conditional",
    "stress testing": "stress testing",
    "stylus": "stylus",
    "subscription": "subscription",
    "sumo logic": "sumo logic",
    "supabase": "supabase",
    "support vector machine": "svm",
    "svm": "svm",
    "swaret": "swaret",
    "swc": "swc",
    "swift": "swift",
    "swift package manager": "swift package manager",
    "swiftui": "swiftui",
    "switches": "switches",
    "switching costs": "switching costs",
    "swr": "swr",
    "system testing": "system testing",
    "t5": "t5",
    "tableau": "tableau",
    "tailwind": "tailwind css",
    "tailwind css": "tailwind css",
    "tailwindcss": "tailwind css",
    "tanstack query": "tanstack query",
    "task": "task",
    "task parallel library": "tpl",
    "tau testing": "tau testing",
    "td3": "td3",
    "teamcity": "teamcity",
    "tekton": "tekton",
    "tencent cloud": "tencent cloud",
    "tensorflow": "tensorflow",
    "terminal": "terminal",
    "terraform": "terraform",
    "test automation": "test automation",
    "test engineering": "test engineering",
    "testcafe": "testcafe",
    "testflight": "testflight",
    "testpypi": "testpypi",
    "text classification": "text classification",
    "textfile": "textfile",
    "tf": "tensorflow",
    "tfs": "tfs",
    "theta testing": "theta testing",
    "thread": "thread",
    "thread pool": "threadpool",
    "threading": "threading",
    "threadpool": "threadpool",
    "three.js": "three.js",
    "threejs": "three.js",
    "thrift": "thrift",
    "tianshou": "tianshou",
    "tilt": "tilt",
    "tipping": "tipping",
    "tls": "ssl/tls",
    "toml": "toml",
    "tomlfile": "tomlfile",
    "tools.deps": "tools.deps",
    "topic modeling": "topic modeling",
    "torch": "pytorch",
    "tpl": "tpl",
    "traefik": "traefik",
    "transactional memory": "transactional memory",
    "transactional synchronization extensions": "tsx",
    "transformers": "transformers",
    "trizen": "trizen",
    "ts": "typescript",
    "tsne": "t-sne",
    "tsv": "tsv",
    "tsvfile": "tsvfile",
    "tsx": "tsx",
    "turbopack": "turbopack",
    "twine": "twine",
    "two sided markets": "two-sided markets",
    "tyk": "tyk",
    "typescript": "typescript",
    "uat": "uat",
    "ui": "ui design",
    "ui design": "ui design",
    "umap": "umap",
    "unity": "unity",
    "unity ml agents": "unity ml-agents",
    "unity3d": "unity",
    "unix": "linux",
    "unleash": "unleash",
    "unreal": "unreal engine",
    "unreal engine": "unreal engine",
    "upgradepkg": "upgradepkg",
    "upsilon testing": "upsilon testing",
    "usability testing": "usability testing",
    "user acceptance testing": "uat",
    "user research": "user research",
    "uv": "uv",
    "ux": "ux design",
    "ux design": "ux design",
    "vae": "vae",
    "vaex": "vaex",
    "vagrant": "vagrant",
    "valtio": "valtio",
    "vault": "vault",
    "vector database": "vector databases",
    "vector databases": "vector databases",
    "vercel functions": "vercel functions",
    "vertex ai": "vertex ai",
    "victory": "victory",
    "visx": "visx",
    "vite": "vite",
    "volatile": "volatile",
    "voting": "voting",
    "vsts": "azure devops",
    "vultr": "vultr",
    "vwo": "vwo",
    "wait free": "wait-free",
    "wandb": "wandb",
    "weaviate": "weaviate",
    "web api": "web api",
    "web3": "web3",
    "webdriver": "webdriver",
    "webhook": "webhooks",
    "webhooks": "webhooks",
    "webpack": "webpack",
    "websocket": "websockets",
    "websockets": "websockets",
    "weights and biases": "wandb",
    "welfare economics": "welfare economics",
    "wheel": "wheel",
    "whisper": "whisper",
    "winget": "winget",
    "wireframing": "wireframing",
    "wireshark": "wireshark",
    "woodpecker": "woodpecker ci",
    "word embeddings": "word embeddings",
    "word2vec": "word2vec",
    "workflow": "workflow",
    "xamarin": "xamarin",
    "xarray": "xarray",
    "xbps": "xbps",
    "xcode": "xcode",
    "xd": "adobe xd",
    "xgboost": "xgboost",
    "xi testing": "xi testing",
    "xml": "xml",
    "xmlfile": "xmlfile",
    "xstate": "xstate",
    "yalp store": "yalp store",
    "yaml": "yaml",
    "yamlfile": "yamlfile",
    "yarn": "yarn",
    "yay": "yay",
    "yolo": "yolo",
    "yum": "yum",
    "yup": "yup",
    "zarr": "zarr",
    "zeplin": "zeplin",
    "zeta testing": "zeta testing",
    "zipkin": "zipkin",
    "zod": "zod",
    "zustand": "zustand",
    "zypper": "zypper",
}

SKILL_CATEGORIES = {
    "languages": ["javascript", "typescript", "python", "java", "go", "golang", "c++", "c#", "c", "r programming", "r", "solidity", "dart", "kotlin", "swift", "sql", "html", "css", "bash", "shell", "assembly", "php", "ruby"],
    "frameworks": ["react", "vue", "angular", "express", "express.js", "django", "spring boot", "laravel", "fastapi", "flask", "tailwind css", "tailwind", "bootstrap", "sass", "redux", "zustand", "unity", "unreal engine", "godot", "next.js", "pandas", "numpy", "scikit-learn", "tensorflow", "pytorch", "keras", "hugging face", "transformers", "d3.js", "three.js", "recharts", "socket.io", "websockets"],
    "devops": ["docker", "kubernetes", "terraform", "jenkins", "git", "ci/cd", "ansible", "github", "gitlab", "prometheus", "grafana", "helm", "argocd", "istio", "vault"],
    "cloud": ["aws", "gcp", "azure", "cloud", "lambda", "s3", "ec2", "dynamodb", "cloudfront", "iam", "vpc", "route53"],
    "databases": ["postgresql", "mysql", "mongodb", "redis", "dynamodb", "sqlite", "cassandra", "oracle", "mariadb"]
}

def normalize_skill(skill_name: str) -> str:
    """
    Normalizes any skill alias to its canonical representation using ALIAS_MAP.
    """
    if not skill_name:
        return ""
    clean = skill_name.strip().lower()
    return ALIAS_MAP.get(clean, clean)

def detect_stack(skills_found):
    skills_set = {s.lower().strip() for s in skills_found}
    
    # 1. Primary Stack Detection Rules
    if "mongodb" in skills_set and "express.js" in skills_set and "react" in skills_set and "node.js" in skills_set:
        primary = "MERN Stack"
    elif "mongodb" in skills_set and "angular" in skills_set and "node.js" in skills_set:
        primary = "MEAN Stack"
    elif "django" in skills_set and "react" in skills_set:
        primary = "Django + React Stack"
    elif "django" in skills_set:
        primary = "Django Stack"
    elif "spring boot" in skills_set:
        primary = "Java Spring Boot Stack"
    elif "laravel" in skills_set:
        primary = "PHP Laravel Stack"
    elif "fastapi" in skills_set:
        primary = "FastAPI Stack"
    elif "flask" in skills_set:
        primary = "Flask Stack"
    elif "react" in skills_set and "tailwind css" in skills_set:
        primary = "React + Tailwind Frontend Stack"
    elif "react" in skills_set:
        primary = "React Frontend Stack"
    elif "vue" in skills_set:
        primary = "Vue.js Stack"
    elif "angular" in skills_set:
        primary = "Angular Stack"
    elif "kubernetes" in skills_set or "terraform" in skills_set or "jenkins" in skills_set:
        primary = "Cloud DevOps Container Stack"
    elif "wireshark" in skills_set or "splunk" in skills_set or "siem" in skills_set:
        primary = "Security Operations Center (SOC) Stack"
    elif "pandas" in skills_set or "numpy" in skills_set or "scikit-learn" in skills_set or "tensorflow" in skills_set or "pytorch" in skills_set:
        primary = "Python Data Science Stack"
    elif "unity" in skills_set or "unreal engine" in skills_set:
        primary = "Game Engine Stack"
    elif "solidity" in skills_set or "web3" in skills_set:
        primary = "Web3 Smart Contract Stack"
    elif "rtos" in skills_set or "firmware" in skills_set or "microcontroller" in skills_set:
        primary = "Embedded Systems Stack"
    else:
        primary = "General Software Engineering Stack"
        
    # 2. Secondary Stack Extraction
    secondary = []
    # Cloud providers
    for c in ["aws", "gcp", "azure"]:
        if c in skills_set:
            secondary.append(c.upper())
    # Databases
    for d in ["postgresql", "mysql", "mongodb", "redis", "dynamodb", "sqlite", "cassandra"]:
        if d in skills_set:
            if d == "postgresql":
                secondary.append("PostgreSQL")
            elif d == "sqlite":
                secondary.append("SQLite")
            elif d == "mongodb":
                secondary.append("MongoDB")
            elif d == "dynamodb":
                secondary.append("DynamoDB")
            else:
                secondary.append(d.capitalize())
    # Container / DevOps tools
    for t in ["docker", "kubernetes", "terraform", "jenkins", "git", "ci/cd", "ansible"]:
        if t in skills_set:
            if t == "kubernetes":
                secondary.append("Kubernetes")
            elif t == "ci/cd":
                secondary.append("CI/CD")
            else:
                secondary.append(t.capitalize())
                
    secondary = sorted(list(set(secondary)))
    return primary, secondary
